title: Skullets
description: Technically Driven Comics

remote_theme: daattali/beautiful-jekyll

navbar-links:
  Comics: "skullets"
  About: "about"

plugins:
  - jekyll-remote-theme

collections:
  skullets:
    output: true
    permalink: /skullets/:name/

defaults:
  - scope:
      path: ""
      type: "skullets"
    values:
      layout: post
